package com.isgc.portal.ncr;

public enum NcrRootCauseCategory {
  UNAPPROVED_MATERIAL,
  MATERIAL_DAMAGE,
  IMPROPER_PLANNING,
  DESIGN_DEVIATION,
  INJURY,
  IMS_DEVIATION,
  SPEC_DEVIATION,
  UNAPPROVED_DOCUMENT,
  TRAFFIC_ACCIDENT,
  MISCELLANEOUS
}
